FROM node:20

WORKDIR /home/app

# Copiamos solo lo necesario para resolver dependencias
COPY package*.json ./

# Instalamos todo en la raíz (esto crea node_modules aquí)
RUN npm install

COPY . .

EXPOSE 4000
EXPOSE 5173

CMD ["npm", "run", "dev:docker"]